### ISSUE TITLE
Monitor standby and lock screen issues

### ISSUE THREAD

**Issue by Johnnii360** [phoronix-test-suite/openbenchmarking#10]
Hi Team!

I discovered an issue that affects the monitor standby and lock screen. I had see that the daemon is toggle the screensaver (monitor standby and lock screen). It is better when you detect and enable the game mode instead of toggle the screensaver. Because when you quit an installation process or benchmark with [Ctrl]+[C] than the deamon might be also killed without switch all back on. So I have to delete toggle_screensaver from the config file.

Before I discovered that I wondered why my lock screen is not work anymore nor the display standby. So I got in mind that could be the Phoronix Benchmark.

That's really bad to toggle the screensaver. Please use the game mode so the benchmark is also get a higher priority and isn't affected by other processes. The Game Mode also suppress the screensaver. If a distro don't have the game mode installed just offer it.

**Comment by michaellarabel** [comment]
Yes, deleting toggle_screensaver from the config file works. 

The lockscreen toggling is only an issue if you exit the PTS process abnormally before it has a chance to restore the original settings.

Ultimately systemd-inhibit can help here but there still exists older versions of it on numerous Linux distributions that cause problems running PTS then.

GameMode unfortunately isn't an option - it's not available on some enterprise Linux distributions, users don't necessarily want the higher priority mode / performance governor enforced if that is not their production configuration, etc. Users are welcome to run with gamemode if they want but is not a default plan.
