### ISSUE TITLE
gcc compilation documentation (timed compilation benchmark suite)

### ISSUE THREAD

**Issue by JuliaLawall** [phoronix-test-suite/openbenchmarking#14]
The following page:
https://openbenchmarking.org/innhold/575d2f00fb9f79937b948edcd8bbff053f3980b6

indicates the following in the file pre.sh:

```
cd gcc-9.3.0
./contrib/download_prerequisites
./configure --disable-multilib --enable-checking=release
make defconfig
make clean
```
But I don't see any occurrence of defconfig in the generated make file, and there is no mention of make defconfig in the gcc documentation, eg https://gcc.gnu.org/install/configure.html

**Comment by michaellarabel** [comment]
The "make defconfig" was just a copy/paste remnant with no impact on the test since it was just in a pre-run script. That leftover bit has since been removed in pts/build-gcc-1.3.0.
