### ISSUE TITLE
Remove references to VP8 on the vpxenc test page

### ISSUE THREAD

**Issue by veikk0** [phoronix-test-suite/openbenchmarking#2]
The vpxenc page at https://openbenchmarking.org/test/pts/vpxenc is headlined as "VP8 libvpx Encoding" and the description talks about VP8, but the test has been VP9 only for quite a while.

The description of the PTS test profile is up to date though, so no need for fixes there.

**Comment by michaellarabel** [comment]
This should be fixed now. Formerly vpxenc targeted VP8 but when VP9 was released, it was updated to that. OpenBenchmarking.org happened to have cached the older title for presentation on the website since very rarely do test titles change. Thanks for reporting.
