### ISSUE TITLE
openbenchmarking e-mail never arrives

### ISSUE THREAD

**Issue by nergdron** [phoronix-test-suite/openbenchmarking#4]
I attempted to sign up for a new account, but the confirmation e-mail I need to get never arrived in my gmail inbox (and yes, I checked the spam folder). I tried to sign up again, and I got the same "we've sent you an e-mail" page, but with a message at the top saying "unknown error". so I think there's something broken with the e-mail verification system.

**Comment by nergdron** [comment]
huh, two weeks with the registration system broken and nobody's even looked at this. is openbenchmarking.org dead?

**Comment by nergdron** [comment]
this issue may be a duplicate of #3, but given the site seems to have no maintainer now, it's likely there are other underlying factors at play here.

**Comment by michaellarabel** [comment]
There is a known issue in the authentication system where for a subset of users there is problems registering / resetting accounts. The issue has been under investigation as time allows but is rather a finicky issue and will likely be addressed in a post-10.0 update. But given the limited resources, affecting only a small subset of users, and nearly all OpenBenchmarking.org functionality not needing user access, it hasn't been a priority. The main  use-case for user accounts is if wanting to upload your own test suites / test profiles.

**Comment by Forza-tng** [comment]
Hello @michaellarabel

I tried to sign up yesterday too and I got no email either.

I've made a change to the sqlite benchmark so it fits better with cow and possibly SMR drives better, and wanted to share it.

**Comment by hanhanW** [comment]
Hi @michaellarabel 

I tried to register an account twice this week, but I never got an email yet. Anyone can help on this?

**Comment by michaellarabel** [comment]
There still seems to be an issue with OpenBenchmarking.org emails getting rejected from some email providers, in any case for now I've enabled it so all users should be able to login even if they didn't click the email.

**Comment by hanhanW** [comment]
I can log in now, thanks for the quick help!

**Comment by gardotd426** [comment]
I tried to register, got no email, and I still can't log in. 

Also my automatic uploads from my benchmarks are just blank when opened in OpenBenchmarking.org:

https://openbenchmarking.org/result/2111235-TJ-SMALLPT1817
![Screenshot_20211123_140633](https://user-images.githubusercontent.com/54234607/143088043-c5f101b8-3e69-4078-a022-7ca8f1028501.png)


Every single benchmark I've done in the last few months is like that.

**Comment by thevrownguy** [comment]
I am having the same issue as well. I tried different browsers and email providers. No luck.

**Comment by bloodwolfepc** [comment]
Have tried to make one a few months ago and again today. I don't get an email.

**Comment by shrapnelnet** [comment]
same issue here. can confirm i am on a VPN but no indication that this is an issue as POST gives a 200
